FROM allxone/tensorflow-serving-devel-gpu

# Configure container to start serving the /model dir
RUN mkdir /model
VOLUME ["/model"]
EXPOSE 9000
CMD ["tensorflow_model_server","--port=9000","--model_name=model","--model_base_path=/model/"]
